---
version: 2.1

jobs:


  publish-sources:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Publish sources to the Stanza Source Service"
          command: |
            apt-get install jq
            last_release=$(git describe --abbrev=0 --tags --match 'v*[0-9].*[0-9].*[0-9]' HEAD~1)
            changed_plugins=$(git diff --name-only $last_release ./plugins)
            for i in $changed_plugins ; do 
              id=${$(basename $i)%.yaml}
              payload="$(jq -Rs "{contents: ., id: \"${id}\"}" $i)"
              curl \
                -H "Authorization: Bearer $GCLOUD_IDENTITY_TOKEN" \
                -X POST \
                -d "$payload" \
                https://stanza-source-service-enle4clm4a-ue.a.run.app/plugins &
            done
            wait


  test_build_release:
    jobs:
      - publish-sources:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
