---
version: 2.1

jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run: mkdir ./artifacts
      - run:
          name: Create Plugins Zip
          command: zip ./artifacts/stanza-plugins.zip ./plugins/*
      - run:
          name: Create Plugins Tarball
          command: tar -zcvf ./artifacts/stanza-plugins.tar.gz ./plugins/*
      - run:
          name: Write Version File
          command: printf '{"version":"%s"}\n' $CIRCLE_TAG > artifacts/version.json
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GHI_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2

  package_plugins:
    jobs:
      - publish-github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/

